version: '3.4'

services:
  guardiansoftheglobeapi:
    image: guardiansoftheglobeapi:dev
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "GuardiansOfTheGlobeApi"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=/root/.nuget/fallbackpackages
    volumes:
      - C:\Users\USUARIO\Source\Repos\GuardiansOfTheGlobe\GuardiansOfTheGlobeApi\GuardiansOfTheGlobeApi:/app
      - C:\Users\USUARIO\Source\Repos\GuardiansOfTheGlobe\GuardiansOfTheGlobeApi:/src
      - C:\Users\USUARIO\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\USUARIO\.nuget\packages\:/root/.nuget/packages:ro
      - D:\Microsoft Visual Studio\Shared\NuGetPackages:/root/.nuget/fallbackpackages:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages --additionalProbingPath /root/.nuget/fallbackpackages  \"/app/bin/Debug/net6.0/GuardiansOfTheGlobeApi.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true