// <auto-generated />
using System;
using GuardiansOfTheGlobeApi.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GuardiansOfTheGlobeApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230522014032_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GuardiansOfTheGlobeApi.Models.Agenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Evento")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("evento");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<int>("IdHeroe")
                        .HasColumnType("int")
                        .HasColumnName("id_heroe");

                    b.HasKey("Id");

                    b.HasIndex("IdHeroe");

                    b.ToTable("agenda");
                });

            modelBuilder.Entity("GuardiansOfTheGlobeApi.Models.Hero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Debilidades")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("debilidades");

                    b.Property<int?>("Edad")
                        .HasColumnType("int")
                        .HasColumnName("edad");

                    b.Property<string>("Habilidades")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("habilidades");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.Property<string>("RelacionesPersonales")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("relaciones_personales");

                    b.HasKey("Id");

                    b.ToTable("heroes");
                });

            modelBuilder.Entity("GuardiansOfTheGlobeApi.Models.Patrocinador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("IdHeroe")
                        .HasColumnType("int")
                        .HasColumnName("id_heroe");

                    b.Property<double>("Monto")
                        .HasColumnType("float")
                        .HasColumnName("monto");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.Property<string>("OrigenDinero")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("origen_dinero");

                    b.HasKey("Id");

                    b.HasIndex("IdHeroe");

                    b.ToTable("patrocinadores");
                });

            modelBuilder.Entity("GuardiansOfTheGlobeApi.Models.Pelea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("IdHeroe")
                        .HasColumnType("int")
                        .HasColumnName("id_heroe");

                    b.Property<int>("IdVillano")
                        .HasColumnType("int")
                        .HasColumnName("id_villano");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("resultado");

                    b.HasKey("Id");

                    b.HasIndex("IdHeroe");

                    b.HasIndex("IdVillano");

                    b.ToTable("peleas");
                });

            modelBuilder.Entity("GuardiansOfTheGlobeApi.Models.Villano", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Debilidades")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("debilidades");

                    b.Property<int>("Edad")
                        .HasColumnType("int")
                        .HasColumnName("edad");

                    b.Property<string>("Habilidades")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("habilidades");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.Property<string>("Origen")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("origen");

                    b.Property<string>("Poder")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("poder");

                    b.HasKey("Id");

                    b.ToTable("villanos");
                });

            modelBuilder.Entity("GuardiansOfTheGlobeApi.Models.Agenda", b =>
                {
                    b.HasOne("GuardiansOfTheGlobeApi.Models.Hero", "IdHeroeNavigation")
                        .WithMany("Agenda")
                        .HasForeignKey("IdHeroe")
                        .IsRequired()
                        .HasConstraintName("FK__agenda__id_heroe__3E52440B");

                    b.Navigation("IdHeroeNavigation");
                });

            modelBuilder.Entity("GuardiansOfTheGlobeApi.Models.Patrocinador", b =>
                {
                    b.HasOne("GuardiansOfTheGlobeApi.Models.Hero", "IdHeroeNavigation")
                        .WithMany("Patrocinadores")
                        .HasForeignKey("IdHeroe")
                        .IsRequired()
                        .HasConstraintName("FK__patrocina__id_he__412EB0B6");

                    b.Navigation("IdHeroeNavigation");
                });

            modelBuilder.Entity("GuardiansOfTheGlobeApi.Models.Pelea", b =>
                {
                    b.HasOne("GuardiansOfTheGlobeApi.Models.Hero", "IdHeroeNavigation")
                        .WithMany("Peleas")
                        .HasForeignKey("IdHeroe")
                        .IsRequired()
                        .HasConstraintName("FK__peleas__id_heroe__440B1D61");

                    b.HasOne("GuardiansOfTheGlobeApi.Models.Villano", "IdVillanoNavigation")
                        .WithMany("Peleas")
                        .HasForeignKey("IdVillano")
                        .IsRequired()
                        .HasConstraintName("FK__peleas__id_villa__44FF419A");

                    b.Navigation("IdHeroeNavigation");

                    b.Navigation("IdVillanoNavigation");
                });

            modelBuilder.Entity("GuardiansOfTheGlobeApi.Models.Hero", b =>
                {
                    b.Navigation("Agenda");

                    b.Navigation("Patrocinadores");

                    b.Navigation("Peleas");
                });

            modelBuilder.Entity("GuardiansOfTheGlobeApi.Models.Villano", b =>
                {
                    b.Navigation("Peleas");
                });
#pragma warning restore 612, 618
        }
    }
}
